# Generated by Django 5.0.14 on 2025-09-23 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_remove_pedido_productos_pedidoitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="creado_en",
        ),
    ]
